# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leo/Project/OOP_indie_studio_2019

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leo/Project/OOP_indie_studio_2019

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/Project/OOP_indie_studio_2019/CMakeFiles /home/leo/Project/OOP_indie_studio_2019/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leo/Project/OOP_indie_studio_2019/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bomberman

# Build rule for target.
bomberman: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bomberman
.PHONY : bomberman

# fast build rule for target.
bomberman/fast:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/build
.PHONY : bomberman/fast

Sources/Components/Animator.o: Sources/Components/Animator.cpp.o

.PHONY : Sources/Components/Animator.o

# target to build an object file
Sources/Components/Animator.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Animator.cpp.o
.PHONY : Sources/Components/Animator.cpp.o

Sources/Components/Animator.i: Sources/Components/Animator.cpp.i

.PHONY : Sources/Components/Animator.i

# target to preprocess a source file
Sources/Components/Animator.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Animator.cpp.i
.PHONY : Sources/Components/Animator.cpp.i

Sources/Components/Animator.s: Sources/Components/Animator.cpp.s

.PHONY : Sources/Components/Animator.s

# target to generate assembly for a file
Sources/Components/Animator.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Animator.cpp.s
.PHONY : Sources/Components/Animator.cpp.s

Sources/Components/Button.o: Sources/Components/Button.cpp.o

.PHONY : Sources/Components/Button.o

# target to build an object file
Sources/Components/Button.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Button.cpp.o
.PHONY : Sources/Components/Button.cpp.o

Sources/Components/Button.i: Sources/Components/Button.cpp.i

.PHONY : Sources/Components/Button.i

# target to preprocess a source file
Sources/Components/Button.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Button.cpp.i
.PHONY : Sources/Components/Button.cpp.i

Sources/Components/Button.s: Sources/Components/Button.cpp.s

.PHONY : Sources/Components/Button.s

# target to generate assembly for a file
Sources/Components/Button.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Button.cpp.s
.PHONY : Sources/Components/Button.cpp.s

Sources/Components/Collider.o: Sources/Components/Collider.cpp.o

.PHONY : Sources/Components/Collider.o

# target to build an object file
Sources/Components/Collider.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Collider.cpp.o
.PHONY : Sources/Components/Collider.cpp.o

Sources/Components/Collider.i: Sources/Components/Collider.cpp.i

.PHONY : Sources/Components/Collider.i

# target to preprocess a source file
Sources/Components/Collider.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Collider.cpp.i
.PHONY : Sources/Components/Collider.cpp.i

Sources/Components/Collider.s: Sources/Components/Collider.cpp.s

.PHONY : Sources/Components/Collider.s

# target to generate assembly for a file
Sources/Components/Collider.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Collider.cpp.s
.PHONY : Sources/Components/Collider.cpp.s

Sources/Components/Cube.o: Sources/Components/Cube.cpp.o

.PHONY : Sources/Components/Cube.o

# target to build an object file
Sources/Components/Cube.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Cube.cpp.o
.PHONY : Sources/Components/Cube.cpp.o

Sources/Components/Cube.i: Sources/Components/Cube.cpp.i

.PHONY : Sources/Components/Cube.i

# target to preprocess a source file
Sources/Components/Cube.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Cube.cpp.i
.PHONY : Sources/Components/Cube.cpp.i

Sources/Components/Cube.s: Sources/Components/Cube.cpp.s

.PHONY : Sources/Components/Cube.s

# target to generate assembly for a file
Sources/Components/Cube.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Cube.cpp.s
.PHONY : Sources/Components/Cube.cpp.s

Sources/Components/Drawable.o: Sources/Components/Drawable.cpp.o

.PHONY : Sources/Components/Drawable.o

# target to build an object file
Sources/Components/Drawable.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Drawable.cpp.o
.PHONY : Sources/Components/Drawable.cpp.o

Sources/Components/Drawable.i: Sources/Components/Drawable.cpp.i

.PHONY : Sources/Components/Drawable.i

# target to preprocess a source file
Sources/Components/Drawable.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Drawable.cpp.i
.PHONY : Sources/Components/Drawable.cpp.i

Sources/Components/Drawable.s: Sources/Components/Drawable.cpp.s

.PHONY : Sources/Components/Drawable.s

# target to generate assembly for a file
Sources/Components/Drawable.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Drawable.cpp.s
.PHONY : Sources/Components/Drawable.cpp.s

Sources/Components/Image.o: Sources/Components/Image.cpp.o

.PHONY : Sources/Components/Image.o

# target to build an object file
Sources/Components/Image.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Image.cpp.o
.PHONY : Sources/Components/Image.cpp.o

Sources/Components/Image.i: Sources/Components/Image.cpp.i

.PHONY : Sources/Components/Image.i

# target to preprocess a source file
Sources/Components/Image.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Image.cpp.i
.PHONY : Sources/Components/Image.cpp.i

Sources/Components/Image.s: Sources/Components/Image.cpp.s

.PHONY : Sources/Components/Image.s

# target to generate assembly for a file
Sources/Components/Image.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Image.cpp.s
.PHONY : Sources/Components/Image.cpp.s

Sources/Components/Moveable.o: Sources/Components/Moveable.cpp.o

.PHONY : Sources/Components/Moveable.o

# target to build an object file
Sources/Components/Moveable.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Moveable.cpp.o
.PHONY : Sources/Components/Moveable.cpp.o

Sources/Components/Moveable.i: Sources/Components/Moveable.cpp.i

.PHONY : Sources/Components/Moveable.i

# target to preprocess a source file
Sources/Components/Moveable.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Moveable.cpp.i
.PHONY : Sources/Components/Moveable.cpp.i

Sources/Components/Moveable.s: Sources/Components/Moveable.cpp.s

.PHONY : Sources/Components/Moveable.s

# target to generate assembly for a file
Sources/Components/Moveable.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Moveable.cpp.s
.PHONY : Sources/Components/Moveable.cpp.s

Sources/Components/Player.o: Sources/Components/Player.cpp.o

.PHONY : Sources/Components/Player.o

# target to build an object file
Sources/Components/Player.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Player.cpp.o
.PHONY : Sources/Components/Player.cpp.o

Sources/Components/Player.i: Sources/Components/Player.cpp.i

.PHONY : Sources/Components/Player.i

# target to preprocess a source file
Sources/Components/Player.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Player.cpp.i
.PHONY : Sources/Components/Player.cpp.i

Sources/Components/Player.s: Sources/Components/Player.cpp.s

.PHONY : Sources/Components/Player.s

# target to generate assembly for a file
Sources/Components/Player.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Player.cpp.s
.PHONY : Sources/Components/Player.cpp.s

Sources/Components/Text.o: Sources/Components/Text.cpp.o

.PHONY : Sources/Components/Text.o

# target to build an object file
Sources/Components/Text.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Text.cpp.o
.PHONY : Sources/Components/Text.cpp.o

Sources/Components/Text.i: Sources/Components/Text.cpp.i

.PHONY : Sources/Components/Text.i

# target to preprocess a source file
Sources/Components/Text.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Text.cpp.i
.PHONY : Sources/Components/Text.cpp.i

Sources/Components/Text.s: Sources/Components/Text.cpp.s

.PHONY : Sources/Components/Text.s

# target to generate assembly for a file
Sources/Components/Text.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Text.cpp.s
.PHONY : Sources/Components/Text.cpp.s

Sources/Components/Timer.o: Sources/Components/Timer.cpp.o

.PHONY : Sources/Components/Timer.o

# target to build an object file
Sources/Components/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Timer.cpp.o
.PHONY : Sources/Components/Timer.cpp.o

Sources/Components/Timer.i: Sources/Components/Timer.cpp.i

.PHONY : Sources/Components/Timer.i

# target to preprocess a source file
Sources/Components/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Timer.cpp.i
.PHONY : Sources/Components/Timer.cpp.i

Sources/Components/Timer.s: Sources/Components/Timer.cpp.s

.PHONY : Sources/Components/Timer.s

# target to generate assembly for a file
Sources/Components/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Timer.cpp.s
.PHONY : Sources/Components/Timer.cpp.s

Sources/Components/Transform.o: Sources/Components/Transform.cpp.o

.PHONY : Sources/Components/Transform.o

# target to build an object file
Sources/Components/Transform.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Transform.cpp.o
.PHONY : Sources/Components/Transform.cpp.o

Sources/Components/Transform.i: Sources/Components/Transform.cpp.i

.PHONY : Sources/Components/Transform.i

# target to preprocess a source file
Sources/Components/Transform.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Transform.cpp.i
.PHONY : Sources/Components/Transform.cpp.i

Sources/Components/Transform.s: Sources/Components/Transform.cpp.s

.PHONY : Sources/Components/Transform.s

# target to generate assembly for a file
Sources/Components/Transform.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Components/Transform.cpp.s
.PHONY : Sources/Components/Transform.cpp.s

Sources/ECS/Component.o: Sources/ECS/Component.cpp.o

.PHONY : Sources/ECS/Component.o

# target to build an object file
Sources/ECS/Component.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Component.cpp.o
.PHONY : Sources/ECS/Component.cpp.o

Sources/ECS/Component.i: Sources/ECS/Component.cpp.i

.PHONY : Sources/ECS/Component.i

# target to preprocess a source file
Sources/ECS/Component.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Component.cpp.i
.PHONY : Sources/ECS/Component.cpp.i

Sources/ECS/Component.s: Sources/ECS/Component.cpp.s

.PHONY : Sources/ECS/Component.s

# target to generate assembly for a file
Sources/ECS/Component.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Component.cpp.s
.PHONY : Sources/ECS/Component.cpp.s

Sources/ECS/Entity.o: Sources/ECS/Entity.cpp.o

.PHONY : Sources/ECS/Entity.o

# target to build an object file
Sources/ECS/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Entity.cpp.o
.PHONY : Sources/ECS/Entity.cpp.o

Sources/ECS/Entity.i: Sources/ECS/Entity.cpp.i

.PHONY : Sources/ECS/Entity.i

# target to preprocess a source file
Sources/ECS/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Entity.cpp.i
.PHONY : Sources/ECS/Entity.cpp.i

Sources/ECS/Entity.s: Sources/ECS/Entity.cpp.s

.PHONY : Sources/ECS/Entity.s

# target to generate assembly for a file
Sources/ECS/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Entity.cpp.s
.PHONY : Sources/ECS/Entity.cpp.s

Sources/ECS/EntityManager.o: Sources/ECS/EntityManager.cpp.o

.PHONY : Sources/ECS/EntityManager.o

# target to build an object file
Sources/ECS/EntityManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/EntityManager.cpp.o
.PHONY : Sources/ECS/EntityManager.cpp.o

Sources/ECS/EntityManager.i: Sources/ECS/EntityManager.cpp.i

.PHONY : Sources/ECS/EntityManager.i

# target to preprocess a source file
Sources/ECS/EntityManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/EntityManager.cpp.i
.PHONY : Sources/ECS/EntityManager.cpp.i

Sources/ECS/EntityManager.s: Sources/ECS/EntityManager.cpp.s

.PHONY : Sources/ECS/EntityManager.s

# target to generate assembly for a file
Sources/ECS/EntityManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/EntityManager.cpp.s
.PHONY : Sources/ECS/EntityManager.cpp.s

Sources/ECS/System/AnimatorSystem.o: Sources/ECS/System/AnimatorSystem.cpp.o

.PHONY : Sources/ECS/System/AnimatorSystem.o

# target to build an object file
Sources/ECS/System/AnimatorSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/AnimatorSystem.cpp.o
.PHONY : Sources/ECS/System/AnimatorSystem.cpp.o

Sources/ECS/System/AnimatorSystem.i: Sources/ECS/System/AnimatorSystem.cpp.i

.PHONY : Sources/ECS/System/AnimatorSystem.i

# target to preprocess a source file
Sources/ECS/System/AnimatorSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/AnimatorSystem.cpp.i
.PHONY : Sources/ECS/System/AnimatorSystem.cpp.i

Sources/ECS/System/AnimatorSystem.s: Sources/ECS/System/AnimatorSystem.cpp.s

.PHONY : Sources/ECS/System/AnimatorSystem.s

# target to generate assembly for a file
Sources/ECS/System/AnimatorSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/AnimatorSystem.cpp.s
.PHONY : Sources/ECS/System/AnimatorSystem.cpp.s

Sources/ECS/System/ButtonSystem.o: Sources/ECS/System/ButtonSystem.cpp.o

.PHONY : Sources/ECS/System/ButtonSystem.o

# target to build an object file
Sources/ECS/System/ButtonSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ButtonSystem.cpp.o
.PHONY : Sources/ECS/System/ButtonSystem.cpp.o

Sources/ECS/System/ButtonSystem.i: Sources/ECS/System/ButtonSystem.cpp.i

.PHONY : Sources/ECS/System/ButtonSystem.i

# target to preprocess a source file
Sources/ECS/System/ButtonSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ButtonSystem.cpp.i
.PHONY : Sources/ECS/System/ButtonSystem.cpp.i

Sources/ECS/System/ButtonSystem.s: Sources/ECS/System/ButtonSystem.cpp.s

.PHONY : Sources/ECS/System/ButtonSystem.s

# target to generate assembly for a file
Sources/ECS/System/ButtonSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ButtonSystem.cpp.s
.PHONY : Sources/ECS/System/ButtonSystem.cpp.s

Sources/ECS/System/ImageSystem.o: Sources/ECS/System/ImageSystem.cpp.o

.PHONY : Sources/ECS/System/ImageSystem.o

# target to build an object file
Sources/ECS/System/ImageSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ImageSystem.cpp.o
.PHONY : Sources/ECS/System/ImageSystem.cpp.o

Sources/ECS/System/ImageSystem.i: Sources/ECS/System/ImageSystem.cpp.i

.PHONY : Sources/ECS/System/ImageSystem.i

# target to preprocess a source file
Sources/ECS/System/ImageSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ImageSystem.cpp.i
.PHONY : Sources/ECS/System/ImageSystem.cpp.i

Sources/ECS/System/ImageSystem.s: Sources/ECS/System/ImageSystem.cpp.s

.PHONY : Sources/ECS/System/ImageSystem.s

# target to generate assembly for a file
Sources/ECS/System/ImageSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/ImageSystem.cpp.s
.PHONY : Sources/ECS/System/ImageSystem.cpp.s

Sources/ECS/System/MoveSystem.o: Sources/ECS/System/MoveSystem.cpp.o

.PHONY : Sources/ECS/System/MoveSystem.o

# target to build an object file
Sources/ECS/System/MoveSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/MoveSystem.cpp.o
.PHONY : Sources/ECS/System/MoveSystem.cpp.o

Sources/ECS/System/MoveSystem.i: Sources/ECS/System/MoveSystem.cpp.i

.PHONY : Sources/ECS/System/MoveSystem.i

# target to preprocess a source file
Sources/ECS/System/MoveSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/MoveSystem.cpp.i
.PHONY : Sources/ECS/System/MoveSystem.cpp.i

Sources/ECS/System/MoveSystem.s: Sources/ECS/System/MoveSystem.cpp.s

.PHONY : Sources/ECS/System/MoveSystem.s

# target to generate assembly for a file
Sources/ECS/System/MoveSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/MoveSystem.cpp.s
.PHONY : Sources/ECS/System/MoveSystem.cpp.s

Sources/ECS/System/PlayerSystem.o: Sources/ECS/System/PlayerSystem.cpp.o

.PHONY : Sources/ECS/System/PlayerSystem.o

# target to build an object file
Sources/ECS/System/PlayerSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/PlayerSystem.cpp.o
.PHONY : Sources/ECS/System/PlayerSystem.cpp.o

Sources/ECS/System/PlayerSystem.i: Sources/ECS/System/PlayerSystem.cpp.i

.PHONY : Sources/ECS/System/PlayerSystem.i

# target to preprocess a source file
Sources/ECS/System/PlayerSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/PlayerSystem.cpp.i
.PHONY : Sources/ECS/System/PlayerSystem.cpp.i

Sources/ECS/System/PlayerSystem.s: Sources/ECS/System/PlayerSystem.cpp.s

.PHONY : Sources/ECS/System/PlayerSystem.s

# target to generate assembly for a file
Sources/ECS/System/PlayerSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/PlayerSystem.cpp.s
.PHONY : Sources/ECS/System/PlayerSystem.cpp.s

Sources/ECS/System/RenderSystem.o: Sources/ECS/System/RenderSystem.cpp.o

.PHONY : Sources/ECS/System/RenderSystem.o

# target to build an object file
Sources/ECS/System/RenderSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/RenderSystem.cpp.o
.PHONY : Sources/ECS/System/RenderSystem.cpp.o

Sources/ECS/System/RenderSystem.i: Sources/ECS/System/RenderSystem.cpp.i

.PHONY : Sources/ECS/System/RenderSystem.i

# target to preprocess a source file
Sources/ECS/System/RenderSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/RenderSystem.cpp.i
.PHONY : Sources/ECS/System/RenderSystem.cpp.i

Sources/ECS/System/RenderSystem.s: Sources/ECS/System/RenderSystem.cpp.s

.PHONY : Sources/ECS/System/RenderSystem.s

# target to generate assembly for a file
Sources/ECS/System/RenderSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/RenderSystem.cpp.s
.PHONY : Sources/ECS/System/RenderSystem.cpp.s

Sources/ECS/System/TextSystem.o: Sources/ECS/System/TextSystem.cpp.o

.PHONY : Sources/ECS/System/TextSystem.o

# target to build an object file
Sources/ECS/System/TextSystem.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/TextSystem.cpp.o
.PHONY : Sources/ECS/System/TextSystem.cpp.o

Sources/ECS/System/TextSystem.i: Sources/ECS/System/TextSystem.cpp.i

.PHONY : Sources/ECS/System/TextSystem.i

# target to preprocess a source file
Sources/ECS/System/TextSystem.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/TextSystem.cpp.i
.PHONY : Sources/ECS/System/TextSystem.cpp.i

Sources/ECS/System/TextSystem.s: Sources/ECS/System/TextSystem.cpp.s

.PHONY : Sources/ECS/System/TextSystem.s

# target to generate assembly for a file
Sources/ECS/System/TextSystem.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/System/TextSystem.cpp.s
.PHONY : Sources/ECS/System/TextSystem.cpp.s

Sources/ECS/Time.o: Sources/ECS/Time.cpp.o

.PHONY : Sources/ECS/Time.o

# target to build an object file
Sources/ECS/Time.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Time.cpp.o
.PHONY : Sources/ECS/Time.cpp.o

Sources/ECS/Time.i: Sources/ECS/Time.cpp.i

.PHONY : Sources/ECS/Time.i

# target to preprocess a source file
Sources/ECS/Time.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Time.cpp.i
.PHONY : Sources/ECS/Time.cpp.i

Sources/ECS/Time.s: Sources/ECS/Time.cpp.s

.PHONY : Sources/ECS/Time.s

# target to generate assembly for a file
Sources/ECS/Time.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/ECS/Time.cpp.s
.PHONY : Sources/ECS/Time.cpp.s

Sources/GameManager.o: Sources/GameManager.cpp.o

.PHONY : Sources/GameManager.o

# target to build an object file
Sources/GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameManager.cpp.o
.PHONY : Sources/GameManager.cpp.o

Sources/GameManager.i: Sources/GameManager.cpp.i

.PHONY : Sources/GameManager.i

# target to preprocess a source file
Sources/GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameManager.cpp.i
.PHONY : Sources/GameManager.cpp.i

Sources/GameManager.s: Sources/GameManager.cpp.s

.PHONY : Sources/GameManager.s

# target to generate assembly for a file
Sources/GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameManager.cpp.s
.PHONY : Sources/GameManager.cpp.s

Sources/GameMenu/GameMenu.o: Sources/GameMenu/GameMenu.cpp.o

.PHONY : Sources/GameMenu/GameMenu.o

# target to build an object file
Sources/GameMenu/GameMenu.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameMenu/GameMenu.cpp.o
.PHONY : Sources/GameMenu/GameMenu.cpp.o

Sources/GameMenu/GameMenu.i: Sources/GameMenu/GameMenu.cpp.i

.PHONY : Sources/GameMenu/GameMenu.i

# target to preprocess a source file
Sources/GameMenu/GameMenu.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameMenu/GameMenu.cpp.i
.PHONY : Sources/GameMenu/GameMenu.cpp.i

Sources/GameMenu/GameMenu.s: Sources/GameMenu/GameMenu.cpp.s

.PHONY : Sources/GameMenu/GameMenu.s

# target to generate assembly for a file
Sources/GameMenu/GameMenu.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/GameMenu/GameMenu.cpp.s
.PHONY : Sources/GameMenu/GameMenu.cpp.s

Sources/InputManager.o: Sources/InputManager.cpp.o

.PHONY : Sources/InputManager.o

# target to build an object file
Sources/InputManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/InputManager.cpp.o
.PHONY : Sources/InputManager.cpp.o

Sources/InputManager.i: Sources/InputManager.cpp.i

.PHONY : Sources/InputManager.i

# target to preprocess a source file
Sources/InputManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/InputManager.cpp.i
.PHONY : Sources/InputManager.cpp.i

Sources/InputManager.s: Sources/InputManager.cpp.s

.PHONY : Sources/InputManager.s

# target to generate assembly for a file
Sources/InputManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/InputManager.cpp.s
.PHONY : Sources/InputManager.cpp.s

Sources/Map/Generation.o: Sources/Map/Generation.cpp.o

.PHONY : Sources/Map/Generation.o

# target to build an object file
Sources/Map/Generation.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Generation.cpp.o
.PHONY : Sources/Map/Generation.cpp.o

Sources/Map/Generation.i: Sources/Map/Generation.cpp.i

.PHONY : Sources/Map/Generation.i

# target to preprocess a source file
Sources/Map/Generation.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Generation.cpp.i
.PHONY : Sources/Map/Generation.cpp.i

Sources/Map/Generation.s: Sources/Map/Generation.cpp.s

.PHONY : Sources/Map/Generation.s

# target to generate assembly for a file
Sources/Map/Generation.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Generation.cpp.s
.PHONY : Sources/Map/Generation.cpp.s

Sources/Map/Map.o: Sources/Map/Map.cpp.o

.PHONY : Sources/Map/Map.o

# target to build an object file
Sources/Map/Map.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Map.cpp.o
.PHONY : Sources/Map/Map.cpp.o

Sources/Map/Map.i: Sources/Map/Map.cpp.i

.PHONY : Sources/Map/Map.i

# target to preprocess a source file
Sources/Map/Map.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Map.cpp.i
.PHONY : Sources/Map/Map.cpp.i

Sources/Map/Map.s: Sources/Map/Map.cpp.s

.PHONY : Sources/Map/Map.s

# target to generate assembly for a file
Sources/Map/Map.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Map/Map.cpp.s
.PHONY : Sources/Map/Map.cpp.s

Sources/Scenes/GameScene.o: Sources/Scenes/GameScene.cpp.o

.PHONY : Sources/Scenes/GameScene.o

# target to build an object file
Sources/Scenes/GameScene.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/GameScene.cpp.o
.PHONY : Sources/Scenes/GameScene.cpp.o

Sources/Scenes/GameScene.i: Sources/Scenes/GameScene.cpp.i

.PHONY : Sources/Scenes/GameScene.i

# target to preprocess a source file
Sources/Scenes/GameScene.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/GameScene.cpp.i
.PHONY : Sources/Scenes/GameScene.cpp.i

Sources/Scenes/GameScene.s: Sources/Scenes/GameScene.cpp.s

.PHONY : Sources/Scenes/GameScene.s

# target to generate assembly for a file
Sources/Scenes/GameScene.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/GameScene.cpp.s
.PHONY : Sources/Scenes/GameScene.cpp.s

Sources/Scenes/LunchGame.o: Sources/Scenes/LunchGame.cpp.o

.PHONY : Sources/Scenes/LunchGame.o

# target to build an object file
Sources/Scenes/LunchGame.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/LunchGame.cpp.o
.PHONY : Sources/Scenes/LunchGame.cpp.o

Sources/Scenes/LunchGame.i: Sources/Scenes/LunchGame.cpp.i

.PHONY : Sources/Scenes/LunchGame.i

# target to preprocess a source file
Sources/Scenes/LunchGame.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/LunchGame.cpp.i
.PHONY : Sources/Scenes/LunchGame.cpp.i

Sources/Scenes/LunchGame.s: Sources/Scenes/LunchGame.cpp.s

.PHONY : Sources/Scenes/LunchGame.s

# target to generate assembly for a file
Sources/Scenes/LunchGame.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/LunchGame.cpp.s
.PHONY : Sources/Scenes/LunchGame.cpp.s

Sources/Scenes/MenuScene.o: Sources/Scenes/MenuScene.cpp.o

.PHONY : Sources/Scenes/MenuScene.o

# target to build an object file
Sources/Scenes/MenuScene.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/MenuScene.cpp.o
.PHONY : Sources/Scenes/MenuScene.cpp.o

Sources/Scenes/MenuScene.i: Sources/Scenes/MenuScene.cpp.i

.PHONY : Sources/Scenes/MenuScene.i

# target to preprocess a source file
Sources/Scenes/MenuScene.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/MenuScene.cpp.i
.PHONY : Sources/Scenes/MenuScene.cpp.i

Sources/Scenes/MenuScene.s: Sources/Scenes/MenuScene.cpp.s

.PHONY : Sources/Scenes/MenuScene.s

# target to generate assembly for a file
Sources/Scenes/MenuScene.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/MenuScene.cpp.s
.PHONY : Sources/Scenes/MenuScene.cpp.s

Sources/Scenes/Scene.o: Sources/Scenes/Scene.cpp.o

.PHONY : Sources/Scenes/Scene.o

# target to build an object file
Sources/Scenes/Scene.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/Scene.cpp.o
.PHONY : Sources/Scenes/Scene.cpp.o

Sources/Scenes/Scene.i: Sources/Scenes/Scene.cpp.i

.PHONY : Sources/Scenes/Scene.i

# target to preprocess a source file
Sources/Scenes/Scene.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/Scene.cpp.i
.PHONY : Sources/Scenes/Scene.cpp.i

Sources/Scenes/Scene.s: Sources/Scenes/Scene.cpp.s

.PHONY : Sources/Scenes/Scene.s

# target to generate assembly for a file
Sources/Scenes/Scene.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Scenes/Scene.cpp.s
.PHONY : Sources/Scenes/Scene.cpp.s

Sources/SoundManager.o: Sources/SoundManager.cpp.o

.PHONY : Sources/SoundManager.o

# target to build an object file
Sources/SoundManager.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/SoundManager.cpp.o
.PHONY : Sources/SoundManager.cpp.o

Sources/SoundManager.i: Sources/SoundManager.cpp.i

.PHONY : Sources/SoundManager.i

# target to preprocess a source file
Sources/SoundManager.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/SoundManager.cpp.i
.PHONY : Sources/SoundManager.cpp.i

Sources/SoundManager.s: Sources/SoundManager.cpp.s

.PHONY : Sources/SoundManager.s

# target to generate assembly for a file
Sources/SoundManager.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/SoundManager.cpp.s
.PHONY : Sources/SoundManager.cpp.s

Sources/Thread/Thread.o: Sources/Thread/Thread.cpp.o

.PHONY : Sources/Thread/Thread.o

# target to build an object file
Sources/Thread/Thread.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/Thread.cpp.o
.PHONY : Sources/Thread/Thread.cpp.o

Sources/Thread/Thread.i: Sources/Thread/Thread.cpp.i

.PHONY : Sources/Thread/Thread.i

# target to preprocess a source file
Sources/Thread/Thread.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/Thread.cpp.i
.PHONY : Sources/Thread/Thread.cpp.i

Sources/Thread/Thread.s: Sources/Thread/Thread.cpp.s

.PHONY : Sources/Thread/Thread.s

# target to generate assembly for a file
Sources/Thread/Thread.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/Thread.cpp.s
.PHONY : Sources/Thread/Thread.cpp.s

Sources/Thread/ThreadPool.o: Sources/Thread/ThreadPool.cpp.o

.PHONY : Sources/Thread/ThreadPool.o

# target to build an object file
Sources/Thread/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/ThreadPool.cpp.o
.PHONY : Sources/Thread/ThreadPool.cpp.o

Sources/Thread/ThreadPool.i: Sources/Thread/ThreadPool.cpp.i

.PHONY : Sources/Thread/ThreadPool.i

# target to preprocess a source file
Sources/Thread/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/ThreadPool.cpp.i
.PHONY : Sources/Thread/ThreadPool.cpp.i

Sources/Thread/ThreadPool.s: Sources/Thread/ThreadPool.cpp.s

.PHONY : Sources/Thread/ThreadPool.s

# target to generate assembly for a file
Sources/Thread/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/Thread/ThreadPool.cpp.s
.PHONY : Sources/Thread/ThreadPool.cpp.s

Sources/main.o: Sources/main.cpp.o

.PHONY : Sources/main.o

# target to build an object file
Sources/main.cpp.o:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/main.cpp.o
.PHONY : Sources/main.cpp.o

Sources/main.i: Sources/main.cpp.i

.PHONY : Sources/main.i

# target to preprocess a source file
Sources/main.cpp.i:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/main.cpp.i
.PHONY : Sources/main.cpp.i

Sources/main.s: Sources/main.cpp.s

.PHONY : Sources/main.s

# target to generate assembly for a file
Sources/main.cpp.s:
	$(MAKE) -f CMakeFiles/bomberman.dir/build.make CMakeFiles/bomberman.dir/Sources/main.cpp.s
.PHONY : Sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... bomberman"
	@echo "... edit_cache"
	@echo "... Sources/Components/Animator.o"
	@echo "... Sources/Components/Animator.i"
	@echo "... Sources/Components/Animator.s"
	@echo "... Sources/Components/Button.o"
	@echo "... Sources/Components/Button.i"
	@echo "... Sources/Components/Button.s"
	@echo "... Sources/Components/Collider.o"
	@echo "... Sources/Components/Collider.i"
	@echo "... Sources/Components/Collider.s"
	@echo "... Sources/Components/Cube.o"
	@echo "... Sources/Components/Cube.i"
	@echo "... Sources/Components/Cube.s"
	@echo "... Sources/Components/Drawable.o"
	@echo "... Sources/Components/Drawable.i"
	@echo "... Sources/Components/Drawable.s"
	@echo "... Sources/Components/Image.o"
	@echo "... Sources/Components/Image.i"
	@echo "... Sources/Components/Image.s"
	@echo "... Sources/Components/Moveable.o"
	@echo "... Sources/Components/Moveable.i"
	@echo "... Sources/Components/Moveable.s"
	@echo "... Sources/Components/Player.o"
	@echo "... Sources/Components/Player.i"
	@echo "... Sources/Components/Player.s"
	@echo "... Sources/Components/Text.o"
	@echo "... Sources/Components/Text.i"
	@echo "... Sources/Components/Text.s"
	@echo "... Sources/Components/Timer.o"
	@echo "... Sources/Components/Timer.i"
	@echo "... Sources/Components/Timer.s"
	@echo "... Sources/Components/Transform.o"
	@echo "... Sources/Components/Transform.i"
	@echo "... Sources/Components/Transform.s"
	@echo "... Sources/ECS/Component.o"
	@echo "... Sources/ECS/Component.i"
	@echo "... Sources/ECS/Component.s"
	@echo "... Sources/ECS/Entity.o"
	@echo "... Sources/ECS/Entity.i"
	@echo "... Sources/ECS/Entity.s"
	@echo "... Sources/ECS/EntityManager.o"
	@echo "... Sources/ECS/EntityManager.i"
	@echo "... Sources/ECS/EntityManager.s"
	@echo "... Sources/ECS/System/AnimatorSystem.o"
	@echo "... Sources/ECS/System/AnimatorSystem.i"
	@echo "... Sources/ECS/System/AnimatorSystem.s"
	@echo "... Sources/ECS/System/ButtonSystem.o"
	@echo "... Sources/ECS/System/ButtonSystem.i"
	@echo "... Sources/ECS/System/ButtonSystem.s"
	@echo "... Sources/ECS/System/ImageSystem.o"
	@echo "... Sources/ECS/System/ImageSystem.i"
	@echo "... Sources/ECS/System/ImageSystem.s"
	@echo "... Sources/ECS/System/MoveSystem.o"
	@echo "... Sources/ECS/System/MoveSystem.i"
	@echo "... Sources/ECS/System/MoveSystem.s"
	@echo "... Sources/ECS/System/PlayerSystem.o"
	@echo "... Sources/ECS/System/PlayerSystem.i"
	@echo "... Sources/ECS/System/PlayerSystem.s"
	@echo "... Sources/ECS/System/RenderSystem.o"
	@echo "... Sources/ECS/System/RenderSystem.i"
	@echo "... Sources/ECS/System/RenderSystem.s"
	@echo "... Sources/ECS/System/TextSystem.o"
	@echo "... Sources/ECS/System/TextSystem.i"
	@echo "... Sources/ECS/System/TextSystem.s"
	@echo "... Sources/ECS/Time.o"
	@echo "... Sources/ECS/Time.i"
	@echo "... Sources/ECS/Time.s"
	@echo "... Sources/GameManager.o"
	@echo "... Sources/GameManager.i"
	@echo "... Sources/GameManager.s"
	@echo "... Sources/GameMenu/GameMenu.o"
	@echo "... Sources/GameMenu/GameMenu.i"
	@echo "... Sources/GameMenu/GameMenu.s"
	@echo "... Sources/InputManager.o"
	@echo "... Sources/InputManager.i"
	@echo "... Sources/InputManager.s"
	@echo "... Sources/Map/Generation.o"
	@echo "... Sources/Map/Generation.i"
	@echo "... Sources/Map/Generation.s"
	@echo "... Sources/Map/Map.o"
	@echo "... Sources/Map/Map.i"
	@echo "... Sources/Map/Map.s"
	@echo "... Sources/Scenes/GameScene.o"
	@echo "... Sources/Scenes/GameScene.i"
	@echo "... Sources/Scenes/GameScene.s"
	@echo "... Sources/Scenes/LunchGame.o"
	@echo "... Sources/Scenes/LunchGame.i"
	@echo "... Sources/Scenes/LunchGame.s"
	@echo "... Sources/Scenes/MenuScene.o"
	@echo "... Sources/Scenes/MenuScene.i"
	@echo "... Sources/Scenes/MenuScene.s"
	@echo "... Sources/Scenes/Scene.o"
	@echo "... Sources/Scenes/Scene.i"
	@echo "... Sources/Scenes/Scene.s"
	@echo "... Sources/SoundManager.o"
	@echo "... Sources/SoundManager.i"
	@echo "... Sources/SoundManager.s"
	@echo "... Sources/Thread/Thread.o"
	@echo "... Sources/Thread/Thread.i"
	@echo "... Sources/Thread/Thread.s"
	@echo "... Sources/Thread/ThreadPool.o"
	@echo "... Sources/Thread/ThreadPool.i"
	@echo "... Sources/Thread/ThreadPool.s"
	@echo "... Sources/main.o"
	@echo "... Sources/main.i"
	@echo "... Sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

